GET http://localhost:5122

###
GET http://localhost:5122/games

###
GET http://localhost:5122/games/1

###
POST http://localhost:5122/games
Content-Type: application/json

{
  "Name": "Call of Duty: Vanguard",
  "GenreId": 3,
  "Price": 59.99,
  "ReleaseDate": "2021-11-05"
}

###
POST http://localhost:5122/games
Content-Type: application/json

{
  "Genre": "Shooter",
  "Price": 59.99,
  "ReleaseDate": "2021-12-08"
}

###
PUT http://localhost:5122/games/1
Content-Type: application/json

{
    "Name": "The Legend of Zelda: BOTW Switch 2 Edition",
    "GenreId": 1,
    "Price": 79.99,
    "ReleaseDate": "2025-08-12"
}

###
PUT http://localhost:5122/games/1
Content-Type: application/json

{
    "Name": "The Legend of Zelda: Breath of the Wild Switch 2 Edition",
    "Price": -1,
    "ReleaseDate": "2025-08-12"
}

###
DELETE http://localhost:5122/games/10

###
GET http://localhost:5122/games/genre/1
