// <auto-generated />
using System;
using GameStore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameStore.API.Data.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    [Migration("20251124215741_seedingBaseData")]
    partial class seedingBaseData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameStore.API.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 2,
                            Name = "The Legend of Zelda: Breath of the Wild",
                            Price = 59.99m,
                            ReleaseDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 1,
                            Name = "God of War",
                            Price = 59.99m,
                            ReleaseDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 3,
                            Name = "The Witcher 3: Wild Hunt",
                            Price = 39.99m,
                            ReleaseDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 4,
                            Name = "Microsoft Flight Simulator",
                            Price = 49.99m,
                            ReleaseDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 5,
                            Name = "FIFA 22",
                            Price = 59.99m,
                            ReleaseDate = new DateOnly(1, 1, 1)
                        });
                });

            modelBuilder.Entity("GameStore.API.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sports"
                        });
                });

            modelBuilder.Entity("GameStore.API.Entities.Game", b =>
                {
                    b.HasOne("GameStore.API.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
